# Generated by Django 3.0.5 on 2020-04-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20, verbose_name='部门昵称')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=30, verbose_name='资产编号')),
                ('asset_type', models.CharField(max_length=30, verbose_name='资产分类')),
                ('asset_name', models.CharField(max_length=20, verbose_name='资产名称')),
                ('asset_buyin_time', models.DateTimeField(verbose_name='财务入账日期')),
                ('asset_value', models.CharField(max_length=20, verbose_name='资产价值')),
                ('asset_state', models.CharField(blank=True, max_length=10, verbose_name='使用情况')),
                ('asset_user', models.CharField(blank=True, max_length=20, verbose_name='使用人')),
                ('asset_count', models.CharField(max_length=20, verbose_name='数量')),
                ('asset_brand', models.CharField(blank=True, max_length=30, verbose_name='资产品牌')),
                ('asset_model', models.CharField(blank=True, max_length=30, verbose_name='规格型号')),
                ('asset_location', models.CharField(blank=True, max_length=40, verbose_name='资产位置')),
                ('asset_comments', models.TextField(blank=True, verbose_name='资产详情')),
                ('asset_use_department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ace.Department')),
            ],
            options={
                'ordering': ('-asset_buyin_time',),
            },
        ),
    ]
