# Generated by Django 3.0.5 on 2020-04-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='departm',
            new_name='department',
        ),
    ]
